# GEMM benchmarking configuration file
gemm_tests:
  # Basic test cases bf16bf16f32of32
  - name: "medium_matrix"
    a_type: "bf16"
    b_type: "bf16"
    c_type: "f32"
    acc_type: "f32"
    storage_format: "row-major"
    transA: false
    transB: true
    # Non optional
    m: [160, 256, 512]
    n: [160, 256, 512]
    k: [160, 256, 512]
    alpha: [2.5, 0, -2.5]
    beta: [2.5, 0, -2.5]
    # Optional Params
    lda: [160, 512, 16000]
    ldb: [160, 512, 16000]
    ldc: [160, 512, 16000]
    mtagA: ["none","pack","pack"]
    mtagB: ["reorder","pack","none"]   # Matrix B reordering can improve performance
    tolerances:
      relative: 100.0
      absolute: 50.0
    product_type: "simple"
  # Basic test cases bf16bf16f32obf16
  - name: "medium_matrix"
    a_type: "bf16"
    b_type: "bf16"
    c_type: "bf16"
    acc_type: "f32"
    storage_format: "row-major"
    transA: false
    transB: true
    # Non optional
    m: [160, 256, 512]
    n: [160, 256, 512]
    k: [160, 256, 512]
    alpha: [2.5, 0, -2.5]
    beta: [2.5, 0, -2.5]
    # Optional Params
    lda: [160, 512, 16000]
    ldb: [160, 512, 16000]
    ldc: [160, 512, 16000]
    mtagA: ["none","pack","pack"]
    mtagB: ["reorder","pack","none"]   # Matrix B reordering can improve performance
    tolerances:
      relative: 200.0
      absolute: 50.0
    product_type: "simple"
