repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v20.1.5'
    hooks:
    -   id: clang-format
        types_or: [c, c++]
        exclude: third_party/

- repo: local
  hooks:
    - id: copyright-checker
      name: Copyright Checker
      entry: scripts/copyright/copyright-checker.py
      language: script
      types_or: [c, c++]
      exclude: third_party/
      pass_filenames: true
      verbose: true

# - repo: https://github.com/pocc/pre-commit-hooks
#   rev: v1.3.5
#   hooks:
    # - id: clang-format
    #   args: [--style=Google]
    # - id: clang-tidy
    # - id: oclint
    # - id: uncrustify
    # - id: cppcheck
    #   types_or: [c++]
    #   exclude: classic/JIT/xbyak
      # files: \.(c|cpp|h|hpp)$
      # args:
      #   - --std=c11
      #   - --std=c++17
      #   - --enable=all
      #   - --inconclusive
      #   - --force
      #   - --error-exitcode=1
    # - id: cpplint
    # - id: include-what-you-use
