/*******************************************************************************
 * Copyright © Advanced Micro Devices, Inc., or its affiliates.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

#ifndef AOCL_DLP_JIT_AMDZEN_STORE_EMIT_HH
#define AOCL_DLP_JIT_AMDZEN_STORE_EMIT_HH

#include "../jit_generator_utils.hh"
#include "gemm_store_emitter.hh"
#include "gemv_m1_store_emitter.hh"
#include "gemv_n1_store_emitter.hh"
#include "jit/jit_generator_base.hh"
#include "xbyak/xbyak.h"

namespace amdzen::store {

// Single-entry, compile-time family-selected store dispatch. The request type
// selects the family; there is no runtime branch. Each overload forwards to the
// existing family emitter, whose explicit template instantiation provides the
// linked implementation, so these inline wrappers add no generated bytes.

template<utils::kernelInstrType KType>
inline dlp::jit::jitGeneratorError
emit(Xbyak::CodeGenerator& jit, const GemmStoreRequest& request)
{
    if constexpr (KType == utils::kernelInstrType::avx512_zmm_32_reg) {
        return GemmStoreEmitter<KType>(jit).emit(request);
    }
    return dlp::jit::jitGeneratorError::notSupported;
}

template<utils::kernelInstrType KType>
inline dlp::jit::jitGeneratorError
emit(Xbyak::CodeGenerator& jit, const GemvM1StoreRequest& request)
{
    if constexpr (KType == utils::kernelInstrType::avx512_zmm_32_reg) {
        return GemvM1StoreEmitter<KType>(jit).emit(request);
    }
    return dlp::jit::jitGeneratorError::notSupported;
}

template<utils::kernelInstrType KType>
inline dlp::jit::jitGeneratorError
emit(Xbyak::CodeGenerator& jit, const GemvN1StoreRequest& request)
{
    if constexpr (KType == utils::kernelInstrType::avx512_zmm_32_reg) {
        return GemvN1StoreEmitter<KType>(jit).emit(request);
    }
    return dlp::jit::jitGeneratorError::notSupported;
}

} // namespace amdzen::store

#endif // AOCL_DLP_JIT_AMDZEN_STORE_EMIT_HH
