name: Branch Name Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_branch_name:
    runs-on: branch_check_linux  # Using your self-hosted runner labeled 'branch_check_linux'

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check branch name using Bash
      env:
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        USER: ${{ github.actor }}
      run: |
        echo "Actor USER: $USER"
        echo "Checking branch name: $BRANCH_NAME"
        # Use case-insensitive regex by converting branch name to lowercase
        LOWER_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
        LOWER_USER=$(echo "$USER" | tr '[:upper:]' '[:lower:]')

        # Accept branch names with any username in the format 'u/<username>/pr/*' or 'u/<username>/wip/*'
        PR_PATTERN="^u/.+/pr/"
        WIP_PATTERN="^u/.+/wip/"

        if [[ "${LOWER_BRANCH_NAME}" =~ $PR_PATTERN ]]; then
          echo "Branch name '$BRANCH_NAME' is recognized as a PR branch."
        elif [[ "${LOWER_BRANCH_NAME}" =~ $WIP_PATTERN ]]; then
          echo "Branch name '$BRANCH_NAME' is recognized as a WIP branch."
        else
          echo "Error: Branch name '$BRANCH_NAME' does not match required naming conventions 'u/<username>/pr/*' or 'u/<username>/wip/*'. Examples: 'u/johndoe/pr/feature', 'u/amy/wip/test'."
          exit 1
        fi
      shell: bash
